# @package _global_

algorithm:
  _target_: "gfn_maxent_rl.algos.soft_qlearning.SoftQLearning"

  network: ${policy_network}

  target: "periodic"
  target_kwargs:
    update_period: 1000

reward_correction: true
